# Generated by Django 4.0.4 on 2022-05-28 16:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100, verbose_name='Заметка')),
                ('status', models.IntegerField(choices=[(1, 'Активно'), (2, 'Отложено'), (3, 'Выполнено')], default=1, verbose_name='Статус')),
                ('importance', models.BooleanField(default=False, verbose_name='Важно')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('note_date', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 19, 7, 47, 353858), verbose_name='Дата и время')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
