# Generated by Django 4.0.4 on 2022-05-31 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_note_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['note_date__date', 'importance']},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='note_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 1, 54, 34, 731811), verbose_name='Дата и время'),
        ),
    ]
